name: mosfeqanik
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  dio: ^4.0.4
  google_fonts: ^2.3.1
  flutter_easyloading: ^3.0.3
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/
   - assets/category_images/